name: WizardPortals
main: com.modwiz.wizardportals.WizardPortals
version: 1.0.0
depends: [WorldEdit]
commands:
    wp:
        usage: See "/wp help" for help.
        description: WizardPortals command set